### ISSUE TITLE
‘class cv::ShapeContextDistanceExtractor’ has no member named ‘getLatestMatches’ Error

### ISSUE THREAD

**Issue by alasin** [luannd/TIRVisReg#1]
OpenCV 3 doesn't seem to have this function. 

https://github.com/luannd/TIRVisReg/blob/506c48497a6a16d75caa808887610b71183a312e/MultimodalVideoRegistrAlg.cpp#L182

**Comment by luannd** [comment]
Hi,
The version OpenCV I used is 3.0.0-rc1. Which version did you use?
